name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "hello word"
            - name: multiline command
              run: |
                npm -v
                ndoe -v

