name: workflow-commands
on: [push]
jobs:
    testing-wf-commands:
         runs-on: ununtu-latest
         steps:
            - name: setting an error message
              run: echo "::error::Missing semicolon"